name:                benchmarks
version:             0.1.0.0
dependencies:
  - base >= 4.7 && < 5
  - monad-par
  - statefulness
  - criterion
  - statistics
  - aeson
  - bytestring
  - process
  - vector
  - hashmap
  - deepseq
  - mtl
  - time
  - monad-par-extras
<<<<<<< HEAD
  - parallel
  - array
=======
  - array
  - parallel
>>>>>>> b0056db92cc0368b39ff52e3c634b97313ee352d
library:
  source-dirs: src # This folder is for shared modules

executables:
  benchmarks:
    main: src/bench_runner.hs
