name:                benchmarks
version:             0.1.0.0
dependencies:
  - base >= 4.7 && < 5
  - monad-par
  - statefulness
  - aeson
  - bytestring
  - process
  - vector
  - hashmap
  - deepseq
  - mtl
  - time
  - monad-par-extras
  - parallel
  - array
  - binary
  - optparse-applicative
  - directory
  - clock
library:
  source-dirs: src # This folder is for shared modules

executables:
  bench-exec:
    dependencies:
      - benchmarks
    main: src/benchmarks.hs
    ghc-options:
      - -rtsopts
      - -threaded
  benchmarks:
    main: src/bench_runner.hs
    dependencies:
      - benchmarks
